/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Duc Lam
 */
public class Bai8QlyDiem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai8QlyDiem.class.getName());
    private ArrayList<Student> danhSach = new ArrayList<>();
    private DefaultTableModel model;

    

    public Bai8QlyDiem() {
        initComponents();

    setTitle("QUẢN LÝ ĐIỂM SINH VIÊN");
    setLocationRelativeTo(null);

    model = (DefaultTableModel) tblSinhVien.getModel();

    txtDiemTB.setEditable(false);
    txtXepLoai.setEditable(false);

    // Xóa các dòng trống có sẵn trong JTable
    model.setRowCount(0);

    // Sự kiện nút
    btnThem.addActionListener(e -> themSinhVien());
    btnSua.addActionListener(e -> suaSinhVien());
    btnXoa.addActionListener(e -> xoaSinhVien());
    btnLamMoi.addActionListener(e -> lamMoi());

    // Khi click vào bảng
    tblSinhVien.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            hienThiLenForm();
        }
    });
    }

    /**
     * Creates new form Bai8QlyDiem
     */
 
        
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtChuyenCan = new javax.swing.JTextField();
        txtGiuaKy = new javax.swing.JTextField();
        txtCuoiKy = new javax.swing.JTextField();
        txtDiemTB = new javax.swing.JTextField();
        txtXepLoai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sinh viên:");

        jLabel2.setText("Họ tên :");

        jLabel3.setText("Điểm chuyên cần :");

        jLabel4.setText("Điểm giữ kỳ : ");

        jLabel5.setText("Điểm cuối kỳ :");

        jLabel6.setText("Điểm trung bình :");

        jLabel7.setText("Xếp lọai :");

        txtMaSV.addActionListener(this::txtMaSVActionPerformed);

        txtChuyenCan.addActionListener(this::txtChuyenCanActionPerformed);

        btnThem.setText("Thêm");

        btnSua.setText("Sửa");

        btnXoa.setText("Xóa");

        btnLamMoi.setText("Làm mới");

        jLabel8.setText("QUẢN LÝ ĐIỂM SINH VIÊN");

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Điểm CC", "Điểm GK", "Điểm CK", "Điểm TB", "Xếp Loại"
            }
        ));
        jScrollPane1.setViewportView(tblSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuoiKy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiuaKy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLamMoi)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSVActionPerformed

    private void txtChuyenCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuyenCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuyenCanActionPerformed
 

    private Student layDuLieu() {

        String maSV = txtMaSV.getText().trim();
    String hoTen = txtHoTen.getText().trim();

    if (maSV.isEmpty() || hoTen.isEmpty()
            || txtChuyenCan.getText().trim().isEmpty()
            || txtGiuaKy.getText().trim().isEmpty()
            || txtCuoiKy.getText().trim().isEmpty()) {

        throw new IllegalArgumentException(
                "Vui lòng nhập đầy đủ thông tin!"
        );
    }

    double chuyenCan = Double.parseDouble(
            txtChuyenCan.getText().trim()
    );

    double giuaKy = Double.parseDouble(
            txtGiuaKy.getText().trim()
    );

    double cuoiKy = Double.parseDouble(
            txtCuoiKy.getText().trim()
    );

    if (chuyenCan < 0 || chuyenCan > 10
            || giuaKy < 0 || giuaKy > 10
            || cuoiKy < 0 || cuoiKy > 10) {

        throw new IllegalArgumentException(
                "Điểm phải nằm trong khoảng từ 0 đến 10!"
        );
    }

    return new Student(
            maSV,
            hoTen,
            chuyenCan,
            giuaKy,
            cuoiKy
    );
}


private void themSinhVien() {

    try {
        String maSV = txtMaSV.getText().trim();

        // Kiểm tra trùng mã sinh viên
        for (Student sv : danhSach) {
            if (sv.getMaSV().equalsIgnoreCase(maSV)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Mã sinh viên đã tồn tại!"
                );
                return;
            }
        }

        Student sv = layDuLieu();

        danhSach.add(sv);

        hienThiBang();
        lamMoi();

        JOptionPane.showMessageDialog(
                this,
                "Thêm sinh viên thành công!"
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Điểm phải là số!"
        );

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}


private void suaSinhVien() {

    int row = tblSinhVien.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn sinh viên cần sửa!"
        );
        return;
    }

    try {

        Student sv = layDuLieu();

        danhSach.set(row, sv);

        hienThiBang();

        JOptionPane.showMessageDialog(
                this,
                "Sửa thành công!"
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Điểm phải là số!"

        );

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}


private void xoaSinhVien() {

    int row = tblSinhVien.getSelectedRow();

    if (row == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn sinh viên cần xóa!"
        );

        return;
    }

    int chon = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc muốn xóa sinh viên này không?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION
    );

    if (chon == JOptionPane.YES_OPTION) {

        danhSach.remove(row);

        hienThiBang();

        lamMoi();

        JOptionPane.showMessageDialog(
                this,
                "Xóa thành công!"
        );
    }
}


private void hienThiBang() {

    model.setRowCount(0);

    for (Student sv : danhSach) {

        model.addRow(new Object[]{
            sv.getMaSV(),
            sv.getHoTen(),
            sv.getDiemChuyenCan(),
            sv.getDiemGiuaKy(),
            sv.getDiemCuoiKy(),
            String.format("%.2f", sv.getDiemTrungBinh()),
            sv.getXepLoai()
        });
    }
}


private void hienThiLenForm() {

    int row = tblSinhVien.getSelectedRow();

    if (row >= 0 && row < danhSach.size()) {

        Student sv = danhSach.get(row);

        txtMaSV.setText(sv.getMaSV());

        txtHoTen.setText(sv.getHoTen());

        txtChuyenCan.setText(
                String.valueOf(sv.getDiemChuyenCan())
        );

        txtGiuaKy.setText(
                String.valueOf(sv.getDiemGiuaKy())
        );

        txtCuoiKy.setText(
                String.valueOf(sv.getDiemCuoiKy())
        );

        txtDiemTB.setText(
                String.format(
                        "%.2f",
                        sv.getDiemTrungBinh()
                )
        );

        txtXepLoai.setText(
                sv.getXepLoai()
        );
    }
}


private void lamMoi() {

    txtMaSV.setText("");
    txtHoTen.setText("");
    txtChuyenCan.setText("");
    txtGiuaKy.setText("");
    txtCuoiKy.setText("");
    txtDiemTB.setText("");
    txtXepLoai.setText("");

    tblSinhVien.clearSelection();

    txtMaSV.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        for (javax.swing.UIManager.LookAndFeelInfo info
                : javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );
                break;
            }
        }

    } catch (ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex) {

        logger.log(
                java.util.logging.Level.SEVERE,
                null,
                ex
        );
    }

    java.awt.EventQueue.invokeLater(() ->
        new Bai8QlyDiem().setVisible(true)
    );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtChuyenCan;
    private javax.swing.JTextField txtCuoiKy;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtGiuaKy;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtXepLoai;
    // End of variables declaration//GEN-END:variables
}