/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Duc Lam
 */
public class BaiDongHo extends javax.swing.JFrame {
     

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BaiDongHo.class.getName());

    /**
     * Creates new form BaiDongHo
     */
    public BaiDongHo() {
         initComponents();

        setTitle("Đồng hồ đếm ngược");
        setLocationRelativeTo(null);

        // Xóa nội dung mặc định
        txtSeconds.setText("");

        // Hiển thị ban đầu
        lblTime.setText("Thời gian còn lại: 0 giây");

        // Bắt sự kiện nút Bắt đầu
        btnStart.addActionListener(e -> startCountdown());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeconds = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSeconds.setText("Nhập số giây cần đếm:");

        btnStart.setText("Bắt đầu");

        lblTime.setText("Thời gian còn lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTime)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {
            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()
                    ) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex
                ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BaiDongHo().setVisible(true));
         new BaiDongHo().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtSeconds;
    // End of variables declaration//GEN-END:variables

    
    private void startCountdown() {

        int seconds;

        // Lấy số giây người dùng nhập
        try {

            seconds = Integer.parseInt(
                    txtSeconds.getText().trim()
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập số nguyên!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Kiểm tra số giây
        if (seconds <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập số giây lớn hơn 0!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Khóa nút Bắt đầu
        btnStart.setEnabled(false);

        // Tạo SwingWorker
        SwingWorker<Void, Integer> worker
                = new SwingWorker<Void, Integer>() {

            @Override
            protected Void doInBackground() throws Exception {

                // Đếm ngược
                for (int i = seconds; i >= 0; i--) {

                    // Gửi dữ liệu lên giao diện
                    publish(i);

                    // Chờ 1 giây
                    if (i > 0) {
                        Thread.sleep(1000);
                    }
                }

                return null;
            }

            @Override
            protected void process(
                    java.util.List<Integer> values) {

                // Lấy giá trị mới nhất
                int time = values.get(
                        values.size() - 1
                );

                // Cập nhật JLabel
                lblTime.setText(
                        "Thời gian còn lại: "
                        + time
                        + " giây"
                );
            }

            @Override
            protected void done() {

                // Khi đếm xong
                lblTime.setText("Hết giờ!");

                // Cho phép bấm lại
                btnStart.setEnabled(true);
            }
        };

        // Chạy SwingWorker
        worker.execute();
    }
}
