/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Duc Lam
 */
public class BaiMoPhong extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BaiMoPhong.class.getName());

    /**
     * Creates new form BaiMoPhong
     */
    public BaiMoPhong() {
        initComponents();
    setTitle("Mô phỏng tiến trình tải dữ liệu");
        setLocationRelativeTo(null);

        // Thiết lập ban đầu
        jButton1.setText("Tải dữ liệu");
        jProgressBar1.setValue(0);
        jLabel1.setText("Sẵn sàng tải dữ liệu");

        // Sự kiện nút
        jButton1.addActionListener(e -> startDownload());
    }

    /**
     * Hàm mô phỏng tải dữ liệu
     */
    private void startDownload() {

        // Khóa nút khi đang tải
        jButton1.setEnabled(false);

        // Đưa thanh tiến trình về 0%
        jProgressBar1.setValue(0);

        // Hiển thị trạng thái
        jLabel1.setText("Đang tải dữ liệu...");

        // Tạo SwingWorker
        javax.swing.SwingWorker<Void, Integer> worker
                = new javax.swing.SwingWorker<Void, Integer>() {

            @Override
            protected Void doInBackground() throws Exception {

                // Tải trong 10 giây
                // 100 lần x 100ms = 10 giây
                for (int i = 0; i <= 100; i++) {

                    Thread.sleep(100);

                    // Gửi tiến độ
                    publish(i);
                }

                return null;
            }

            @Override
            protected void process(
                    java.util.List<Integer> values) {

                // Lấy giá trị tiến độ mới nhất
                int progress
                        = values.get(values.size() - 1);

                // Cập nhật ProgressBar
                jProgressBar1.setValue(progress);

                // Cập nhật trạng thái
                jLabel1.setText(
                        "Đang tải: " + progress + "%"
                );
            }

            @Override
            protected void done() {

                // Hoàn thành
                jProgressBar1.setValue(100);

                jLabel1.setText(
                        "Tải dữ liệu hoàn tất!"
                );

                // Cho phép bấm lại
                jButton1.setEnabled(true);
            }
        };

        // Bắt đầu SwingWorker
        worker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jLabel1.setText("Hiển thị trạng thái");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()
                    ) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex
                ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BaiMoPhong().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
